# fly.toml file generated for marcados on 2023-04-17T12:17:55-05:00

app = "marcados"
primary_region = "bog"

[http_service]
  internal_port = 8080
  force_https = true

[checks]
  [checks.alive]
    type = "tcp"
    interval = "15s"
    timeout = "2s"
    grace_period = "5s"

[build]
  image = "heroku/buildpacks:18"
  builder = "heroku/buildpacks"
  buildpacks = [
    "heroku/python"
  ]
