# Generated by Django 3.2.16 on 2023-04-12 15:00

import apps.perfil.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0002_alter_userprofile_country_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(default='users/user_default_profile.jpg', upload_to=apps.perfil.models.user_directory_path_profile),
        ),
    ]
