# Generated by Django 3.2.16 on 2023-04-12 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='name',
            field=models.CharField(blank=True, default='admin', max_length=255, null=True, verbose_name='full name'),
        ),
    ]
