# Generated by Django 3.2.16 on 2023-04-11 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.ManyToManyField(blank=True, related_name='blog_post_images', to='blog.Image'),
        ),
    ]
